language: scala
scala:
  - 2.12.4

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coverageReport coveralls

service_name: travis-pro

repo_token: sHpaupiNWFkc2P3f3t5YFYhnN0uTz2HPr