version: "3.9"
services:
  tui:
    container_name: "tui_service"
    build:
      context: ./TUI
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
  fileio:
    container_name: "fileIo_service"
    build:
      context: ./FileIO
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"
  root:
    container_name: "root_service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    environment:
      DISPLAY: host.docker.internal:0
  board-games-postgres:
    container_name: "board-games-postgres"
    build:
      dockerfile: ./localdeployment/docker-local/board-games-postgres/init/Dockerfile
      context: .
    restart: "no"
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
